name: Daily Moodle Check

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          ICAL_URL: ${{ secrets.ICAL_URL }}
        run: python main.py