name: Daily Moodle Check

on:
  push:
  workflow_dispatch:
  schedule:
    # ⚠️ GitHubはUTC（協定世界時）なので、日本時間(JST)から9時間引いた時間を指定します
    - cron: '0 22 * * *' # 日本時間 翌朝 7:00（22+9=31 -> 翌朝7時）
    - cron: '0 3 * * *'  # 日本時間 お昼 12:00（3+9=12）
    - cron: '0 12 * * *' # 日本時間 夜 21:00（12+9=21）

    
jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          ICAL_URL: ${{ secrets.ICAL_URL }}
        run: python main.py